Repository SSHSRN/Seeking-Roots, pull requests merged in 2023-03, with the labels that each got.

#60 Mandatory inputs issue solved
  index.html
  style.css
Labels: JWOC, easy

#62 [feat]:issue #49 (Footer Elements must be in center) has been solved
  footer.css
  index2.html
Labels: JWOC, easy

#72 [Enhancement] Added Google Translator
  footer.css
  index.html
Labels: JWOC, hard

#71 Added testimonial
  assets/images/face1.jpg
  assets/images/face2.jpg
  assets/images/face3.jpg
  assets/images/face4.jpg
  assets/images/face5.jpg
  assets/images/face6.jpg
  assets/images/face7.jpg
  assets/images/face8.jpg
  assets/images/face9.jpg
  home.html
  swiper-bundle.min.css
  swiper-bundle.min.js
  testimonial.css
  testimonial.html
  testimonial.js
Labels: JWOC, hard

#76 preloader added
  assets/images/preloader.gif
  home.html
  index.html
  index2.html
  style.css
Labels: JWOC, medium

#80 Login page improved
  index.html
  style.css
Labels: JWOC, medium

#81 Contributors section added
  README.md
Labels: JWOC, easy

#84 Badges Added
  README.md
Labels: JWOC, easy

#88 Fixed Footer of About Us page
  footer.css
Labels: JWOC, medium

#86 Added customized scrollbar
  biography.css
  footer.css
  home.css
  index1.css
  index2.css
  style.css
  testimonial.css
Labels: JWOC, medium

#90 Placeholder added
  index.html
Labels: JWOC, easy

#92 faq added
  faq.html
  index.html
Labels: JWOC, medium

#93 Issue #89
  home.html
  translate.css
  translate.js
Labels: JWOC, medium

#99 Added about us page
  About.css
  About.html
  home.html
Labels: JWOC, medium

#101 Folder Structuring
  assets/dark-wall-empty-room-with-plants-floor-3d-rendering.jpg
  assets/large_seekingroots.png
  css_files/About.css
  css_files/biography.css
  css_files/footer.css
  css_files/go_to_top.css
  css_files/home.css
  css_files/index1.css
  css_files/index2.css
  css_files/navbar.css
  css_files/style.css
  css_files/swiper-bundle.min.css
  css_files/testimonial.css
  css_files/translate.css
  html_files/About.html
  html_files/biography.html
  html_files/faq.html
  html_files/home.html
  html_files/index1.html
  html_files/index2.html
  html_files/testimonial.html
  index.html
  js_files/functional.js
  js_files/go_to_top.js
  js_files/swiper-bundle.min.js
  js_files/testimonial.js
  js_files/translate.js
Labels: JWOC, easy

#103 Contact page added
  assets/images/contact.jpg
  contact.css
  contact.html
Labels: JWOC, medium

#111 Fixed & Added Hamburger to Navigation Bar
  index.html
Labels: JWOC, medium

#109 counter animation added
  css_files/About.css
  html_files/About.html
Labels: JWOC, medium

#113 Footer Improved
  .footer.css.swp
  css_files/footer.css
  css_files/navbar.css
  index.html
Labels: JWOC, medium

#116 Uniform UI
  css_files/About.css
  css_files/footer.css
  css_files/home.css
  css_files/style.css
  css_files/testimonial.css
  html_files/About.html
  html_files/biography.html
  html_files/faq.html
  html_files/testimonial.html
  index.html
Labels: JWOC, hard

#114 sigIn visibility changed from the index.html file
  CONTRIBUTING.md
  index.html
Labels: JWOC, medium

#117 Updated Faq Section
  css_files/faq.css
  html_files/faq.html
Labels: JWOC, medium

#119 Add profile card
  assets/images/sriharis.jpeg
  css_files/About.css
  html_files/About.html
Labels: JWOC, medium
